CREATE TABLE api_error( 
      id  integer generated by default as identity     NOT NULL , 
      classe varchar  (255)   , 
      metodo varchar  (255)   , 
      url varchar  (500)   , 
      dados varchar  (3000)   , 
      error_message varchar  (3000)   , 
      created_at timestamp   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE categoria( 
      id  integer generated by default as identity     NOT NULL , 
      tipo_conta_id integer    NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE categoria_cliente( 
      id  integer generated by default as identity     NOT NULL , 
      nome varchar  (255)    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE cep_cache( 
      id  integer generated by default as identity     NOT NULL , 
      cep varchar  (10)   , 
      rua varchar  (10)   , 
      cidade varchar  (500)   , 
      bairro varchar  (500)   , 
      codigo_ibge varchar  (20)   , 
      uf varchar  (2)   , 
      cidade_id integer   , 
      estado_id integer   , 
      created_at timestamp   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE cidade( 
      id  integer generated by default as identity     NOT NULL , 
      estado_id integer    NOT NULL , 
      nome varchar  (255)    NOT NULL , 
      codigo_ibge varchar  (10)    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE conta( 
      id  integer generated by default as identity     NOT NULL , 
      pessoa_id integer    NOT NULL , 
      tipo_conta_id integer    NOT NULL , 
      categoria_id integer    NOT NULL , 
      forma_pagamento_id integer    NOT NULL , 
      pedido_venda_id integer   , 
      dt_vencimento date   , 
      dt_emissao date   , 
      dt_pagamento date   , 
      valor float   , 
      parcela integer   , 
      obs blob sub_type 1   , 
      mes_vencimento integer   , 
      ano_vencimento integer   , 
      ano_mes_vencimento integer   , 
      mes_emissao integer   , 
      ano_emissao integer   , 
      ano_mes_emissao integer   , 
      mes_pagamento integer   , 
      ano_pagamento integer   , 
      ano_mes_pagamento integer   , 
      created_at timestamp   , 
      updated_at timestamp   , 
      deleted_at timestamp   , 
      system_unit_id integer   , 
      system_departamento_id integer   , 
      system_entidade_id integer   , 
      natureza_conta_id integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE conta_anexo( 
      id  integer generated by default as identity     NOT NULL , 
      conta_id integer    NOT NULL , 
      tipo_anexo_id integer    NOT NULL , 
      descricao blob sub_type 1   , 
      arquivo blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE dotacao_orcamentaria_conta( 
      id  integer generated by default as identity     NOT NULL , 
      created_at timestamp   , 
      updated_at timestamp   , 
      deleted_at timestamp   , 
      conta_id integer   , 
      system_saldo_empenho_departamento_id integer   , 
      valor float   , 
      saldo_atual float   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE error_log_crontab( 
      id  integer generated by default as identity     NOT NULL , 
      classe blob sub_type 1   , 
      metodo blob sub_type 1   , 
      mensagem blob sub_type 1   , 
      created_at timestamp   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE estado( 
      id  integer generated by default as identity     NOT NULL , 
      nome varchar  (255)    NOT NULL , 
      sigla char  (2)    NOT NULL , 
      codigo_ibge varchar  (10)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE forma_pagamento( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE grupo_pessoa( 
      id  integer generated by default as identity     NOT NULL , 
      nome varchar  (255)    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE natureza_conta( 
      id  integer generated by default as identity     NOT NULL , 
      created_at timestamp   , 
      updated_at timestamp   , 
      deleted_at timestamp   , 
      descricao varchar  (40)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE pessoa( 
      id  integer generated by default as identity     NOT NULL , 
      tipo_cliente_id integer    NOT NULL , 
      categoria_cliente_id integer   , 
      system_user_id integer   , 
      nome varchar  (500)    NOT NULL , 
      documento varchar  (20)    NOT NULL , 
      obs varchar  (1000)   , 
      fone varchar  (255)   , 
      email varchar  (255)   , 
      created_at timestamp   , 
      updated_at timestamp   , 
      deleted_at timestamp   , 
      login varchar  (255)   , 
      senha varchar  (255)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE pessoa_contato( 
      id  integer generated by default as identity     NOT NULL , 
      pessoa_id integer    NOT NULL , 
      email varchar  (255)   , 
      nome varchar  (255)   , 
      telefone varchar  (255)   , 
      obs varchar  (500)   , 
      created_at timestamp   , 
      updated_at timestamp   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE pessoa_departamento( 
      id  integer generated by default as identity     NOT NULL , 
      created_at timestamp   , 
      updated_at timestamp   , 
      deleted_at timestamp   , 
      pessoa_id integer   , 
      system_departamento_id integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE pessoa_endereco( 
      id  integer generated by default as identity     NOT NULL , 
      pessoa_id integer    NOT NULL , 
      cidade_id integer    NOT NULL , 
      nome varchar  (255)   , 
      principal char  (1)   , 
      cep varchar  (10)   , 
      rua varchar  (500)   , 
      numero varchar  (20)   , 
      bairro varchar  (500)   , 
      complemento varchar  (500)   , 
      data_desativacao date   , 
      created_at timestamp   , 
      updated_at timestamp   , 
      longitude varchar  (20)   , 
      latitude varchar  (20)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE pessoa_grupo( 
      id  integer generated by default as identity     NOT NULL , 
      pessoa_id integer    NOT NULL , 
      grupo_pessoa_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_departamento( 
      id  integer generated by default as identity     NOT NULL , 
      created_at timestamp   , 
      updated_at timestamp   , 
      deleted_at timestamp   , 
      system_unit_id integer   , 
      cidade_id integer   , 
      nome blob sub_type 1   , 
      rua varchar  (500)   , 
      cep varchar  (10)   , 
      bairro varchar  (500)   , 
      numero varchar  (20)   , 
      longitude varchar  (20)   , 
      latitude varchar  (20)   , 
      email varchar  (500)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_documentos( 
      id  integer generated by default as identity     NOT NULL , 
      created_at timestamp   , 
      updated_at timestamp   , 
      deleted_at timestamp   , 
      system_unit_id integer   , 
      data date   , 
      mes integer   , 
      ano integer   , 
      arquivo varchar  (500)   , 
      tipo_system_documentos_id integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_entidade( 
      id  integer generated by default as identity     NOT NULL , 
      created_at timestamp   , 
      updated_at timestamp   , 
      deleted_at timestamp   , 
      cnpj varchar  (20)   , 
      nome blob sub_type 1   , 
      email blob sub_type 1   , 
      cep varchar  (10)   , 
      numero varchar  (10)   , 
      rua varchar  (500)   , 
      bairro varchar  (500)   , 
      telefone01 varchar  (20)   , 
      telefone02 varchar  (20)   , 
      longitude varchar  (20)   , 
      latitude varchar  (20)   , 
      logo varchar  (500)   , 
      complemento varchar  (500)   , 
      cidade_id integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_group( 
      id integer    NOT NULL , 
      name blob sub_type 1    NOT NULL , 
      uuid varchar  (36)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_group_program( 
      id integer    NOT NULL , 
      system_group_id integer    NOT NULL , 
      system_program_id integer    NOT NULL , 
      actions blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_preference( 
      id varchar  (255)    NOT NULL , 
      preference blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_program( 
      id integer    NOT NULL , 
      name blob sub_type 1    NOT NULL , 
      controller blob sub_type 1    NOT NULL , 
      actions blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_saldo_empenho_departamento( 
      id  integer generated by default as identity     NOT NULL , 
      created_at timestamp   , 
      updated_at timestamp   , 
      deleted_at timestamp   , 
      system_departamento_id integer   , 
      saldo float   , 
      historico varchar  (500)   , 
      numero_documento_empenho varchar  (500)   , 
      data_documento_empenho date   , 
      numero_processo varchar  (500)   , 
      arquivo_empenho varchar  (500)   , 
      system_users_id integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_unit( 
      id integer    NOT NULL , 
      name blob sub_type 1    NOT NULL , 
      connection_name blob sub_type 1   , 
      email varchar  (500)   , 
      cep varchar  (10)   , 
      rua varchar  (500)   , 
      numero varchar  (10)   , 
      bairro varchar  (500)   , 
      complemento varchar  (500)   , 
      cnpj varchar  (20)   , 
      telefone01 varchar  (50)   , 
      telefone02 varchar  (50)   , 
      logo varchar  (500)   , 
      longitude varchar  (20)   , 
      latitude varchar  (20)   , 
      system_entidade_id integer   , 
      cidade_id integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_user_group( 
      id integer    NOT NULL , 
      system_user_id integer    NOT NULL , 
      system_group_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_user_program( 
      id integer    NOT NULL , 
      system_user_id integer    NOT NULL , 
      system_program_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_users( 
      id integer    NOT NULL , 
      name blob sub_type 1    NOT NULL , 
      login blob sub_type 1    NOT NULL , 
      password blob sub_type 1    NOT NULL , 
      email blob sub_type 1   , 
      frontpage_id integer   , 
      system_unit_id integer   , 
      active char  (1)   , 
      accepted_term_policy_at blob sub_type 1   , 
      accepted_term_policy char  (1)   , 
      two_factor_enabled char  (1)    DEFAULT 'N' , 
      two_factor_type varchar  (100)   , 
      two_factor_secret varchar  (255)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_user_unit( 
      id integer    NOT NULL , 
      system_user_id integer    NOT NULL , 
      system_unit_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE tipo_anexo( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE tipo_cliente( 
      id  integer generated by default as identity     NOT NULL , 
      nome varchar  (255)    NOT NULL , 
      sigla char  (2)    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE tipo_conta( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE tipo_system_documentos( 
      id  integer generated by default as identity     NOT NULL , 
      created_at timestamp   , 
      updated_at timestamp   , 
      deleted_at timestamp   , 
      descricao varchar  (100)   , 
 PRIMARY KEY (id)) ; 

 
  
 ALTER TABLE categoria ADD CONSTRAINT fk_categoria_1 FOREIGN KEY (tipo_conta_id) references tipo_conta(id); 
ALTER TABLE cidade ADD CONSTRAINT fk_cidade_1 FOREIGN KEY (estado_id) references estado(id); 
ALTER TABLE conta ADD CONSTRAINT fk_conta_1 FOREIGN KEY (tipo_conta_id) references tipo_conta(id); 
ALTER TABLE conta ADD CONSTRAINT fk_conta_2 FOREIGN KEY (categoria_id) references categoria(id); 
ALTER TABLE conta ADD CONSTRAINT fk_conta_3 FOREIGN KEY (forma_pagamento_id) references forma_pagamento(id); 
ALTER TABLE conta ADD CONSTRAINT fk_conta_4 FOREIGN KEY (pessoa_id) references pessoa(id); 
ALTER TABLE conta ADD CONSTRAINT fk_conta_5 FOREIGN KEY (system_unit_id) references system_unit(id); 
ALTER TABLE conta ADD CONSTRAINT fk_conta_6 FOREIGN KEY (system_departamento_id) references system_departamento(id); 
ALTER TABLE conta ADD CONSTRAINT fk_conta_7 FOREIGN KEY (system_entidade_id) references system_entidade(id); 
ALTER TABLE conta ADD CONSTRAINT fk_conta_8 FOREIGN KEY (natureza_conta_id) references natureza_conta(id); 
ALTER TABLE conta_anexo ADD CONSTRAINT fk_conta_anexo_1 FOREIGN KEY (conta_id) references conta(id); 
ALTER TABLE conta_anexo ADD CONSTRAINT fk_conta_anexo_2 FOREIGN KEY (tipo_anexo_id) references tipo_anexo(id); 
ALTER TABLE dotacao_orcamentaria_conta ADD CONSTRAINT fk_dotacao_conta_1 FOREIGN KEY (conta_id) references conta(id); 
ALTER TABLE dotacao_orcamentaria_conta ADD CONSTRAINT fk_dotacao_conta_2 FOREIGN KEY (system_saldo_empenho_departamento_id) references system_saldo_empenho_departamento(id); 
ALTER TABLE pessoa ADD CONSTRAINT fk_pessoa_1 FOREIGN KEY (tipo_cliente_id) references tipo_cliente(id); 
ALTER TABLE pessoa ADD CONSTRAINT fk_pessoa_2 FOREIGN KEY (categoria_cliente_id) references categoria_cliente(id); 
ALTER TABLE pessoa ADD CONSTRAINT fk_pessoa_3 FOREIGN KEY (system_user_id) references system_users(id); 
ALTER TABLE pessoa_contato ADD CONSTRAINT fk_pessoa_contato_1 FOREIGN KEY (pessoa_id) references pessoa(id); 
ALTER TABLE pessoa_departamento ADD CONSTRAINT fk_pessoa_departamento_1 FOREIGN KEY (pessoa_id) references pessoa(id); 
ALTER TABLE pessoa_departamento ADD CONSTRAINT fk_pessoa_departamento_2 FOREIGN KEY (system_departamento_id) references system_departamento(id); 
ALTER TABLE pessoa_endereco ADD CONSTRAINT fk_pessoa_endereco_1 FOREIGN KEY (pessoa_id) references pessoa(id); 
ALTER TABLE pessoa_endereco ADD CONSTRAINT fk_pessoa_endereco_2 FOREIGN KEY (cidade_id) references cidade(id); 
ALTER TABLE pessoa_grupo ADD CONSTRAINT fk_pessoa_grupo_1 FOREIGN KEY (pessoa_id) references pessoa(id); 
ALTER TABLE pessoa_grupo ADD CONSTRAINT fk_pessoa_grupo_2 FOREIGN KEY (grupo_pessoa_id) references grupo_pessoa(id); 
ALTER TABLE system_departamento ADD CONSTRAINT fk_system_departamento_1 FOREIGN KEY (system_unit_id) references system_unit(id); 
ALTER TABLE system_departamento ADD CONSTRAINT fk_system_departamento_2 FOREIGN KEY (cidade_id) references cidade(id); 
ALTER TABLE system_documentos ADD CONSTRAINT fk_balancos_1 FOREIGN KEY (system_unit_id) references system_unit(id); 
ALTER TABLE system_documentos ADD CONSTRAINT fk_system_documentos_2 FOREIGN KEY (tipo_system_documentos_id) references tipo_system_documentos(id); 
ALTER TABLE system_entidade ADD CONSTRAINT fk_system_entidade_1 FOREIGN KEY (cidade_id) references cidade(id); 
ALTER TABLE system_group_program ADD CONSTRAINT fk_system_group_program_1 FOREIGN KEY (system_program_id) references system_program(id); 
ALTER TABLE system_group_program ADD CONSTRAINT fk_system_group_program_2 FOREIGN KEY (system_group_id) references system_group(id); 
ALTER TABLE system_saldo_empenho_departamento ADD CONSTRAINT fk_system_saldo_depsec_1 FOREIGN KEY (system_departamento_id) references system_departamento(id); 
ALTER TABLE system_saldo_empenho_departamento ADD CONSTRAINT system_saldo_empenho_departamento_69c18f3ccefd0 FOREIGN KEY (system_users_id) references system_users(id); 
ALTER TABLE system_unit ADD CONSTRAINT fk_system_unit_1 FOREIGN KEY (system_entidade_id) references system_entidade(id); 
ALTER TABLE system_unit ADD CONSTRAINT fk_system_unit_2 FOREIGN KEY (cidade_id) references cidade(id); 
ALTER TABLE system_user_group ADD CONSTRAINT fk_system_user_group_1 FOREIGN KEY (system_group_id) references system_group(id); 
ALTER TABLE system_user_group ADD CONSTRAINT fk_system_user_group_2 FOREIGN KEY (system_user_id) references system_users(id); 
ALTER TABLE system_user_program ADD CONSTRAINT fk_system_user_program_1 FOREIGN KEY (system_program_id) references system_program(id); 
ALTER TABLE system_user_program ADD CONSTRAINT fk_system_user_program_2 FOREIGN KEY (system_user_id) references system_users(id); 
ALTER TABLE system_users ADD CONSTRAINT fk_system_user_1 FOREIGN KEY (system_unit_id) references system_unit(id); 
ALTER TABLE system_users ADD CONSTRAINT fk_system_user_2 FOREIGN KEY (frontpage_id) references system_program(id); 
ALTER TABLE system_user_unit ADD CONSTRAINT fk_system_user_unit_1 FOREIGN KEY (system_user_id) references system_users(id); 
ALTER TABLE system_user_unit ADD CONSTRAINT fk_system_user_unit_2 FOREIGN KEY (system_unit_id) references system_unit(id); 
