[builder]
app_url = "https://app.madbuilder.com.br"
manager_url = "https://code.madbuilder.com.br"
services_url = "https://services.madbuilder.com.br"
version = "4.2"

[general]
timezone = America/Sao_Paulo
language = pt
application = portal_transparencia
title = "Mini Financeiro"
require_terms = 0
theme = theme-builder
dialog_box_type = "bootstrap"
multiunit = 0
change_unit = 0
request_unit_after_login = 0
locale = pt-BR
token = 035f38fe1402246601a7ac90eab46207d5119a49d825fec341025a2c4f7137bcbd328b
seed = cf555f336ea4b176480b93624d5902452c4b5f49
rest_key = e18cdd10eadadbfd8464a369fd4b3d2f8f71c7f277a752aaf130a4cd78ce
debug = 0
multi_lang = "0"
left_menu = "1"
top_menu = "1"
verify_messages_menu = "0"
verify_notifications_menu = "0"
default_units = ""
use_tabs = 0
store_tabs = 0
use_mdi_windows = 0
store_mdi_windows = 0
notification_login = 0
left_menu_modules = "1"
top_menu_modules = "1"
application_version = "Versão 1.0"
main_database = "minierp"

;request_log_service = SystemRequestLogService
;request_log = 1
;request_log_types = cli,web,rest


multi_database = "0"

public_view = "0"
public_entry = "PublicView"
theme_mobile = theme-builder

[user_public_pages]


[permission]

user_register    = "1"  ; users may auto register
reset_password   = "1"  ; users may reset password
default_groups   = "2"  ; default groups for auto registered users
default_units    = "1"  ; default units for auto registered users
default_screen   = "10" ; default screen for auto registered users
single_user_session = 0



; Public classes, anyone (logged or not) has access
public_classes[] = PublicForm
public_classes[] = PublicView
public_classes[] = DatabaseInstall
public_classes[] = ExtensionsInstall
public_classes[] = PathInstall
public_classes[] = SummaryDatabaseInstall
public_classes[] = SystemModulesCheckView
public_classes[] = AdiantiMultiSearchService
public_classes[] = AdiantiUploaderService
public_classes[] = AdiantiAutocompleteService


public_classes[] = SystemRegistrationForm
public_classes[] = SystemPasswordResetForm
public_classes[] = SystemRequestPasswordResetForm